<?php

/**
 * This is the model base class for the table "chatting".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Chatting".
 *
 * Columns in table "chatting" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $chatting_id
 * @property integer $user_id
 * @property integer $user_id_friend
 *
 */
abstract class BaseChatting extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'chatting';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Chatting|Chattings', $n);
	}

	public static function representingColumn() {
		return 'chatting_id';
	}

	public function rules() {
		return array(
			array('chatting_id, user_id, user_id_friend', 'required'),
			array('chatting_id, user_id, user_id_friend', 'numerical', 'integerOnly'=>true),
			array('chatting_id, user_id, user_id_friend', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'chatting_id' => Yii::t('app', 'Chatting'),
			'user_id' => Yii::t('app', 'User'),
			'user_id_friend' => Yii::t('app', 'User Id Friend'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('chatting_id', $this->chatting_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('user_id_friend', $this->user_id_friend);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}