<?php

/**
 * This is the model base class for the table "comment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comment".
 *
 * Columns in table "comment" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $comment_id
 * @property integer $post_id
 * @property integer $user_comment_id
 * @property string $content
 * @property integer $date
 *
 */
abstract class BaseComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comment|Comments', $n);
	}

	public static function representingColumn() {
		return 'content';
	}

	public function rules() {
		return array(
			array('comment_id, post_id, user_comment_id, content, date', 'required'),
			array('comment_id, post_id, user_comment_id, date', 'numerical', 'integerOnly'=>true),
			array('comment_id, post_id, user_comment_id, content, date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'comment_id' => Yii::t('app', 'Comment'),
			'post_id' => Yii::t('app', 'Post'),
			'user_comment_id' => Yii::t('app', 'User Comment'),
			'content' => Yii::t('app', 'Content'),
			'date' => Yii::t('app', 'Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('comment_id', $this->comment_id);
		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('user_comment_id', $this->user_comment_id);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('date', $this->date);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}