<?php

/**
 * This is the model base class for the table "location".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Location".
 *
 * Columns in table "location" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $location_id
 * @property string $name
 * @property double $latitude
 * @property double $longitude
 *
 */
abstract class BaseLocation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'location';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Location|Locations', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('location_id, name, latitude, longitude', 'required'),
			array('location_id', 'numerical', 'integerOnly'=>true),
			array('latitude, longitude', 'numerical'),
			array('name', 'length', 'max'=>255),
			array('location_id, name, latitude, longitude', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'location_id' => Yii::t('app', 'Location'),
			'name' => Yii::t('app', 'Name'),
			'latitude' => Yii::t('app', 'Latitude'),
			'longitude' => Yii::t('app', 'Longitude'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('latitude', $this->latitude);
		$criteria->compare('longitude', $this->longitude);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}